"""
ai_reasoning.py
Turns raw indicator/signal data into a short, plain-English explanation for the
Telegram alert -- same pattern used in the football prediction bot's explanation step.

Supports two providers, switched via config.AI_PROVIDER:
  "gemini" (default) -> Google AI Studio, free tier, no credit card required
  "claude"            -> Anthropic API, paid, higher quality reasoning
  "none"               -> skip AI entirely, always use the templated fallback

This is explanation generation, not decision-making: the BUY/SELL/HOLD
signal itself is already decided by strategy.py before this module is called.
The AI is not asked to override or second-guess the signal, only to explain it
and flag anything a trader should watch for.
"""

import config


SYSTEM_PROMPT = """You are a concise trading assistant writing short explanations for a
forex signal alert bot. You are given a signal that has ALREADY been generated by a
rule-based strategy (RSI + MACD + EMA confluence). Your job is only to:

1. Explain in plain English why this combination of indicators produced this signal
2. Briefly note the current volatility context (from ATR)
3. Add ONE honest caveat about what could invalidate this signal

Keep it under 80 words. No disclaimers about not being financial advice needed --
that's handled elsewhere. Do not hedge on whether the signal is correct; just explain
the mechanics and the key risk to watch. Plain, direct language, no fluff, no emojis."""


def generate_explanation(pair: str, signal: str, snapshot: dict, strategy_reasons: list, trade_params: dict) -> str:
    """
    Returns a short natural-language explanation string.
    Routes to the configured provider; falls back to a templated explanation
    if the provider is disabled, unconfigured, or the API call fails.
    """
    user_prompt = f"""Pair: {pair}
Signal: {signal}
Indicator snapshot: {snapshot}
Conditions that triggered this signal: {strategy_reasons}
Trade parameters: {trade_params}

Write the explanation now."""

    provider = config.AI_PROVIDER

    if provider == "gemini" and config.GEMINI_API_KEY:
        result = _generate_with_gemini(user_prompt)
        if result:
            return result

    elif provider == "claude" and config.ANTHROPIC_API_KEY:
        result = _generate_with_claude(user_prompt)
        if result:
            return result

    # provider == "none", missing key, or the API call failed above
    return _fallback_explanation(signal, strategy_reasons)


def _generate_with_gemini(user_prompt: str) -> str:
    """Calls Google's Gemini API (free tier via Google AI Studio)."""
    try:
        import google.generativeai as genai

        genai.configure(api_key=config.GEMINI_API_KEY)
        model = genai.GenerativeModel(
            model_name=config.GEMINI_MODEL,
            system_instruction=SYSTEM_PROMPT,
        )
        response = model.generate_content(user_prompt)
        text = (response.text or "").strip()
        return text if text else ""

    except Exception as e:
        print(f"[GEMINI ERROR] Falling back to templated explanation: {e}")
        return ""


def _generate_with_claude(user_prompt: str) -> str:
    """Calls Anthropic's Claude API (paid)."""
    try:
        import anthropic

        client = anthropic.Anthropic(api_key=config.ANTHROPIC_API_KEY)
        response = client.messages.create(
            model=config.CLAUDE_MODEL,
            max_tokens=200,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_prompt}],
        )
        text_blocks = [b.text for b in response.content if b.type == "text"]
        return "\n".join(text_blocks).strip()

    except Exception as e:
        print(f"[CLAUDE ERROR] Falling back to templated explanation: {e}")
        return ""


def _fallback_explanation(signal: str, strategy_reasons: list) -> str:
    """Simple templated explanation used if no AI provider is configured or available."""
    reasons_str = "; ".join(strategy_reasons) if strategy_reasons else "multiple indicator conditions aligned"
    return f"{signal} signal triggered because: {reasons_str}. As always, treat this as one input among several -- no indicator combination guarantees the outcome."
