"""
ai_reasoning.py
Turns raw indicator/signal data into a short, plain-English explanation for
the Telegram alert. Supports Gemini (free, default) or Claude (paid,
optional) via AI_PROVIDER, or "none" to skip AI entirely and use the
templated fallback with zero API calls.

This is explanation generation, not decision-making: the BUY/SELL/HOLD
signal itself is already decided by strategy.py before this module is
called -- the AI is never asked to override or second-guess it.
"""

import config

SYSTEM_PROMPT = """You are a concise trading assistant writing short explanations for a
forex signal alert bot. You are given a signal that has ALREADY been generated by a
rule-based strategy (RSI + MACD + EMA confluence, with a session and ADX trend-strength
filter). Your job is only to:

1. Explain in plain English why this combination of indicators produced this signal
2. Briefly note the current volatility context (from ATR)
3. Add ONE honest caveat about what could invalidate this signal

Keep it under 80 words. Do not hedge on whether the signal is correct; just explain
the mechanics and the key risk to watch. Plain, direct language, no fluff, no emojis."""


def generate_explanation(pair: str, signal: str, snapshot: dict, strategy_reasons: list, trade_params: dict) -> str:
    """Returns a short natural-language explanation string, per AI_PROVIDER."""
    provider = config.AI_PROVIDER

    if provider == "none":
        return _fallback_explanation(signal, strategy_reasons)

    if provider == "gemini" and config.GEMINI_API_KEY:
        result = _try_gemini(pair, signal, snapshot, strategy_reasons, trade_params)
        if result:
            return result

    if provider == "claude" and config.ANTHROPIC_API_KEY:
        result = _try_claude(pair, signal, snapshot, strategy_reasons, trade_params)
        if result:
            return result

    return _fallback_explanation(signal, strategy_reasons)


def _build_prompt(pair, signal, snapshot, strategy_reasons, trade_params) -> str:
    return f"""Pair: {pair}
Signal: {signal}
Indicator snapshot: {snapshot}
Conditions that triggered this signal: {strategy_reasons}
Trade parameters: {trade_params}

Write the explanation now."""


def _try_gemini(pair, signal, snapshot, strategy_reasons, trade_params):
    try:
        import google.generativeai as genai

        genai.configure(api_key=config.GEMINI_API_KEY)
        model = genai.GenerativeModel(
            model_name=config.GEMINI_MODEL,
            system_instruction=SYSTEM_PROMPT,
        )
        prompt = _build_prompt(pair, signal, snapshot, strategy_reasons, trade_params)
        response = model.generate_content(prompt)
        text = (response.text or "").strip()
        return text if text else None
    except Exception as e:
        print(f"[GEMINI ERROR] Falling back to templated explanation: {e}")
        return None


def _try_claude(pair, signal, snapshot, strategy_reasons, trade_params):
    try:
        import anthropic

        client = anthropic.Anthropic(api_key=config.ANTHROPIC_API_KEY)
        prompt = _build_prompt(pair, signal, snapshot, strategy_reasons, trade_params)
        response = client.messages.create(
            model=config.CLAUDE_MODEL,
            max_tokens=200,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": prompt}],
        )
        text_blocks = [b.text for b in response.content if b.type == "text"]
        text = "\n".join(text_blocks).strip()
        return text if text else None
    except Exception as e:
        print(f"[CLAUDE ERROR] Falling back to templated explanation: {e}")
        return None


def _fallback_explanation(signal: str, strategy_reasons: list) -> str:
    reasons_str = "; ".join(strategy_reasons) if strategy_reasons else "multiple indicator conditions aligned"
    return (
        f"{signal} signal triggered because: {reasons_str}. As always, treat this "
        f"as one input among several -- no indicator combination guarantees the outcome."
    )
