"""
claude_reasoning.py
Calls the Anthropic API to turn raw indicator/signal data into a short,
plain-English explanation for the Telegram alert -- the same pattern used
in the football prediction bot's explanation step.

This is explanation generation, not decision-making: the BUY/SELL/HOLD
signal itself is already decided by strategy.py before this module is called.
Claude is not asked to override or second-guess the signal, only to explain it
and to flag anything a trader should watch for.
"""

import anthropic
import config


SYSTEM_PROMPT = """You are a concise trading assistant writing short explanations for a
forex signal alert bot. You are given a signal that has ALREADY been generated by a
rule-based strategy (RSI + MACD + EMA confluence). Your job is only to:

1. Explain in plain English why this combination of indicators produced this signal
2. Briefly note the current volatility context (from ATR)
3. Add ONE honest caveat about what could invalidate this signal

Keep it under 80 words. No disclaimers about not being financial advice needed --
that's handled elsewhere. Do not hedge on whether the signal is correct; just explain
the mechanics and the key risk to watch. Plain, direct language, no fluff, no emojis."""


def generate_explanation(pair: str, signal: str, snapshot: dict, strategy_reasons: list, trade_params: dict) -> str:
    """
    Returns a short natural-language explanation string.
    Falls back to a templated explanation if the API call fails or is disabled.
    """
    if not config.USE_CLAUDE_REASONING or not config.ANTHROPIC_API_KEY:
        return _fallback_explanation(signal, strategy_reasons)

    user_prompt = f"""Pair: {pair}
Signal: {signal}
Indicator snapshot: {snapshot}
Conditions that triggered this signal: {strategy_reasons}
Trade parameters: {trade_params}

Write the explanation now."""

    try:
        client = anthropic.Anthropic(api_key=config.ANTHROPIC_API_KEY)
        response = client.messages.create(
            model=config.CLAUDE_MODEL,
            max_tokens=200,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_prompt}],
        )
        text_blocks = [b.text for b in response.content if b.type == "text"]
        explanation = "\n".join(text_blocks).strip()
        return explanation if explanation else _fallback_explanation(signal, strategy_reasons)

    except Exception as e:
        print(f"[CLAUDE ERROR] Falling back to templated explanation: {e}")
        return _fallback_explanation(signal, strategy_reasons)


def _fallback_explanation(signal: str, strategy_reasons: list) -> str:
    """Simple templated explanation used if Claude is unavailable."""
    reasons_str = "; ".join(strategy_reasons) if strategy_reasons else "multiple indicator conditions aligned"
    return f"{signal} signal triggered because: {reasons_str}. As always, treat this as one input among several -- no indicator combination guarantees the outcome."
